languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "A collection of thoughts, ideas and projects"
dateFormat = "2 January 2006"
logo = "/img/avatar.png"
secondaryLogo = "/img/avatar.png"

[params.author]
name = "Adithya Sudhan"
image = "img/avatar.png"
headline = "A collection of thoughts, ideas and projects"
bio = "Software engineer focused on AI, Cloud and DevOps"
links = [
    { linkedin = "https://www.linkedin.com/in/adithyasudhan/" },
    { github = "https://github.com/xocolatl-aficionado/" }
]
