baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Adithya Sudhan'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Adithya Sudhan"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a Cloud Engineer focused on keeping microservices reliably deployed, and antifragile.
With certifications in **AWS**, production experience in **Azure** and personal work on **GCP**, I've found myself curious about the strengths and weaknesses of various clouds, and how a growing company tackles the trade-off between owning their own cloud vs renting another. Particularly, I'm fascinated by how ubiquitous open source tools like **Kubernetes** and **Terraform**, coupled with paradigms like **C**ontinuous **I**ntegration and standards like **Y**et **A**nother **M**arkup **L**anguage, have transformed the way applications are built, tested and deployed, dramatically reducing production delivery times. 
"""


# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/adithyasudhan/"

[[params.social]]
name = "github"
url = "https://github.com/xocolatl-aficionado/"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"